name: Swift-CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Setup Project
      run: ./setup.sh
    - name: Xcode Build
      run: xcodebuild  -workspace Dayol-iOS.xcworkspace -scheme "Dayol Beta" -destination 'platform=iOS Simulator,name=iPhone 12 mini'
